apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  labels:
    app: ledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: banking-orchestration-platform/ledger-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8084
          envFrom:
            - configMapRef:
                name: payment-platform-config
            - secretRef:
                name: payment-platform-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  labels:
    app: ledger-service
spec:
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 8084
      targetPort: http
