apiVersion: v1
kind: Secret
metadata:
  name: payment-platform-secrets
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  QUERY_DB_USERNAME: postgres
  QUERY_DB_PASSWORD: postgres
  LEDGER_DB_USERNAME: postgres
  LEDGER_DB_PASSWORD: postgres
  NOTIFICATION_DB_USERNAME: postgres
  NOTIFICATION_DB_PASSWORD: postgres
  LIMIT_DB_USERNAME: postgres
  LIMIT_DB_PASSWORD: postgres
