spring:
  application:
    name: payment-query-service
  datasource:
    url: ${QUERY_DB_URL:jdbc:postgresql://localhost:5432/payment_query}
    username: ${QUERY_DB_USERNAME:postgres}
    password: ${QUERY_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${PAYMENT_QUERY_CONSUMER_GROUP:payment-query-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
app:
  payment-events:
    topic: ${PAYMENT_EVENTS_TOPIC:payment.domain.events}
server:
  port: 8082
